### ISSUE TITLE
OCP Details Page Table - Nodes Row Expansion

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#291]
## User Story
As an operations user, I want to view a list of OCP charges grouped by nodes so that I can assess how the OCP charges are broken down by those nodes.

## Impacts
- API
- UI
- Docs

## Role
Operations User

## Assumptions
- API is available for UI consumption
- Data is available to show OCP charges for current month to date and last month's

### Mocks
The following mock is the OCP Details Page Table with a row expanded, grouped by nodes
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822475_OCPCharge-GrpByNode-Expanded

### Textual Description & Related Issues
The table has the following columns:
- Node name/ID
- Change in charge (the delta between the previous month and this month's charge) with an icon to indicate if it went up or down since the last month, plus the change in charge (dollar amount) and textual indication of up or down since last month.
- Charge

Within each row's expanded panel, that content will be...
- A bar chart of the top 3 or 5 (depending on layout restrictions) projects (with the most charge) of that node (Issue #300)
- A bullet graph that shows the CPU usage, requests, limits, and capacity of the selected node (Issue #321)
- A bullet graph that shows the Memory usage, requests, limits, and capacity of the selected node (Issue #320)
- The table should also let the user launch a modal dialog that would contain the historical data (in linear graph) of the total cost, CPU usage, and Memory usage month over month (Issue #322)

## Acceptance Criteria
- [ ] user should view a node's name, change in charge, and charge data
- [ ] user should be able to select a row to expand to reveal more details on a particular node
- [ ] user should be able to launch a modal dialog that will show the node's historical charge, cpu, and memory data.

**Comment by dlabrecq** [comment]
This has been implemented
