### ISSUE TITLE
OCP Details Page

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#295]
## User Story
As a user (operations), I want to see more details of the OpenShift Charges so that I can understand how the usage is broken down by.

## Impacts
- API
- UI
- Docs

## Role
Operations - User

## Assumptions
- APIs are available for the UI to use to get the necessary data to be displayed.

## UI Details
Detailed flow of the OCP Details Page is found in Slides 11 - 22 of the following prototype: https://redhat.invisionapp.com/share/HEO4ISHAT8Z

More specifically, the details page consists of...
- Issue #313 : Header that contains the title of the page, group by selection component, total charge amount, and date the charge is totaled for.
- Issue #304 : Contents section of the page, which should contain the table and it's toolbar.  The Group by control found in the header should be connected to what the table's contents would be.  The format should be relatively similar, but depending on the option selected in the group by control, that will dictate the ultimate data to before found in the table and the row's expansion content.

## Acceptance Criteria
- [ ] the UI has been implemented according to design (link above)
- [ ] the user will be able to view a list of projects and its charges and the difference in charge, month over month
- [ ] the user will be able to view a list of clusters and its charges and the difference in charge, month over month
- [ ] the user will be able to view more information on a project's CPU and Memory usage/request metrics
- [ ] the user will be able to view more information on a project's tags and the cluster they belong to
- [ ] the user should be able to access the selected project's historical metric/charge data
- [ ] the user should be able to filter on project name, cluster name, and tag
- [ ] the user should be able to see a list grouped by projects, clusters, or specifically chosen tag keys
- [ ] the user should be able to sort by project/cluster name, delta, and charge
- [ ] the UI has been functionally tested

**Comment by dlabrecq** [comment]
This has been implemented.
