### ISSUE TITLE
OCP Details Page Table

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#304]
## User Story
As a user (operations), I want to see a table of OpenShift charges group by either project, cluster, node, or a specific tag key, so that I can better see the breakdown of the charges by the selected group by option and drill down from there on possible reasons why the charge is the way it is.

## Impacts
- API
- UI
- Docs

## Role
Operations User

## Assumptions
- APIs are available for the UI to use to get the necessary data to be displayed.

### Mocks
Table grouped by Projects:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822484_OCPCharge-GrpByProj
Table grouped by Clusters:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822473_OCPCharge-GrpByClust
Table grouped by Nodes:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822478_OCPCharge-GrpByNode
Table grouped by a Tag Key: 
TBD

### Textual description
Depending on the selection from the Group by component on the header (Issue #313), the table will have the following columns:
- [Project | Cluster | Node | Tag Key] Name - name of the project, cluster, node, or tag key that is being listed.
- Change in charge (the delta between the previous month and this month's charge) with an icon to indicate if it went up or down since the last month, plus the change in charge (dollar amount) and textual indication of up or down since last month.
- Charge amount (the dollar amount the project, cluster, node, or tag key has summed up to)

### Related Issues
Additional controls of the table can be found in the toolbar, which the following issue will cover:
- Issue #314: Table Toolbar

Contents of the row expansion will be covered in the following issues:
 - Issue #315: Projects
- Issue #317: Clusters
- Issue #291: Nodes
- TBD: Tag Keys

## Acceptance Criteria
- [ ] the UI has been implemented according to design (link above)
- [ ] the UI has been functionally tested
- [x] the user will be able to view a list of projects and its charges and the difference in charge, month over month
- [x] the user will be able to view a list of clusters and its charges and the difference in charge, month over month
- [x] the user will be able to view a list of nodes and its charges and the difference in charge, month over month
- [ ] the user will be able to view a list of selected tag key and its charges and the difference in charge, month over month

**Comment by dlabrecq** [comment]
This has been implemented.
