### ISSUE TITLE
Selected Project's Historical Data Modal

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#305]
## User Story
As an operations user, I want to see a particular project's historical data so that I can compare this month's usage to last month's usage to identify any discrepancies.

## Impacts
- API
- UI
- Docs

## Role
User - Operations

## Assumptions
API is available for UI consumption

### Mocks
The following mock will show what the selected project's historical data modal dialog contents:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/330585330_OCPCharge-GrpByProj-Modal

### Textual Description & Related Issues
In this modal, the following graphs should be seen:
- The selected project's current and previous month's daily cumulative charge (Issue #301)
- The selected project's current and previous month's daily cpu usage, requests, and limits (Issue #302)
- The selected project's current and previous month's daily memory usage, requests and limits (Issue #303)

## Acceptance Criteria
- [ ] User should be able to view the historical (month over month) total cumulative charges of the selected project
- [ ] User should be able to view the historical (month over month) daily CPU usage and request and limits of the selected project
- [ ] User should be able to view the historical (month over month) daily Memory usage and request and limits of the selected project
- [ ] User should be able to exit out of the modal (clicking the "x" button) to then return them to the previous screen (Charge Details Page grouped by Projects)

**Comment by dlabrecq** [comment]
This has been implemented.
