### ISSUE TITLE
Selected Cluster's Historical Data Modal

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#307]
## User Story
As an operations user, I want to see a particular cluster's historical data so that I can compare this month's usage to last month's usage to identify any discrepancies.

## Impacts
- API
- UI
- Docs

## Role
User - Operations

## Assumptions
API is available for UI consumption

### Mocks
The following mock will show what the selected cluster's historical data modal dialog contents:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/330587748_OCPCharge-GrpByClust-Modal

### Textual Description & Related Issues
In this modal, the following graphs should be seen:
- The selected cluster's current and previous month's daily cumulative charge (Issue #306)
- The selected cluster's current and previous month's CPU data (Issue #308)
- The selected cluster's current and previous month's Memory data (Issue #309)

## Acceptance Criteria
- [ ] User should be able to view the historical (month over month) total cumulative charges of the selected cluster
- [ ] User should be able to view the historical (month over month) daily CPU usage and request and limits of the selected cluster
- [ ] User should be able to view the historical (month over month) daily Memory usage and request and limits of the selected cluster
- [ ] User should be able to exit out of the modal (clicking the "x" button) to then return them to the previous screen (Charge Details Page grouped by Cluster)

**Comment by dlabrecq** [comment]
This has been implemented.
