### ISSUE TITLE
OCP Details Page Header

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#313]
## User Story
As an operation user, I want to be able to group OpenShift charges by project, cluster, nodes or a select number of tag keys so that I can view the breakdown of charges by different terms.

## Impacts
- API
- UI
- Docs

## Role
Operation User

## Assumptions
APIs are available for UI consumption

### Mock
The top of this page reveals what the page header would look like:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822484_OCPCharge-GrpByProj

### Textual Description
The header contains a title, "group by" control (Issue #298), and to the far right is the total charge number for OCP current month to date with the dates that covers.

### Related Issues
A portion of the header is a component that controls the content of the table that is on the same page as this header and which completes the page.
- Issue #298: Group by component

## Acceptance Criteria
- [ ] User understands where they are in the application (via title of page)
- [ ] User can access the group by component to change the groupings that are viewed in the table below the header (see dependency for more info)
- [ ] User can view the total OCP charge and date it covers (should coincide with numbers found on the Overview page's total cost card)

**Comment by dlabrecq** [comment]
This has been completed
