### ISSUE TITLE
OCP Details Page Table Toolbar

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#314]
## User Story
As an operations user, I want to be able to filter, sort, and export data from the details table so that find, analyze and export charge details data.

## Impacts
- API
- UI
- Docs

## Role
Operations User

## Assumptions
- API are available for UI consumption
- There is at least previous month and month to date for current months data stored

### Mocks
The following mock is a general view of how the table toolbar's components are laid out:
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822484_OCPCharge-GrpByProj

### Textual Description
The filter by, sort by, and export components that are explained in separate issues (found below). Besides those components, there is (if necessary) a pagination component.

### Related Issues
The following issues will help make up the toolbar, separated them out since linking them with the right APIs might be separate calls to deal with.
- Issue #297: Filter By
- Issue #296: Sort By
- Issue #316: Export

## Acceptance Criteria
- [x] user should be able to filter by a project name (if grouped by project)
- [x] user should be able to filter by a cluster name (if grouped by cluster)
- [x] user should be able to filter by a node name (if grouped by node)
- [ ] user should be able to filter by a tag
- [x] user should be able to sort by the project name (if grouped by project)
- [x] user should be able to sort by the cluster name (if grouped by cluster)
- [x] user should be able to sort by the node name (if grouped by node)
- [x] user should be able to sort by the charge
- [ ] user should be able to sort by the change in charge
- [x] user should be able to export the selected rows (if any selected, if not, then should disallow)

**Comment by dlabrecq** [comment]
Currently, there is no support for filtering by tags and sorting by "change in charge". The functionality has otherwise been completed. 

We may want to create another issue to track unsupported functionality separately?

**Comment by dlabrecq** [comment]
This has been implemented. Clicking on the tag applies a filter.
