### ISSUE TITLE
OCP Details Page Table - Projects Row Expansion 

### ISSUE THREAD

**Issue by nlcwong** [project-koku/koku-ui#315]
## User Story
As an operations user, I want to view a list of OCP charges grouped by projects so that I can assess how the OCP charges are broken down by projects.

## Impacts
- API
- UI
- Docs

## Role
Operations User

## Assumptions
- API is available for UI consumption
- Data is available to show OCP charges for current month to date and last month's

### Mocks
The following mock is the OCP Details Page Table with a row expanded), grouped by Projects
https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/323822482_OCPCharge-GrpByProj-Expanded

### Textual Description & Related Issues
Within each row's expanded panel, that content will be...
- The Cluster name the project is associated with
- A list of tags the project is associated with
- A bullet graph that shows the CPU usage, requests, and limits of the selected project (Issue #292)
- A bullet graph that shows the Memory usage, requests, and limits of the selected project (Issue #293)
- The table should also let the user launch a modal dialog that would contain the historical data (in linear graph) of the total cost, CPU usage, and Memory usage month over month (Issue #305)

## Acceptance Criteria
- [ ] user should view a project's name, change in charge, and charge data
- [ ] user should be able to select a row to expand to reveal more details on a particular project
- [ ] user should be able to launch a modal dialog that will show the project's historical charge, cpu, and memory data.

**Comment by dlabrecq** [comment]
This has been implemented.
