### ISSUE TITLE
Group By Tags

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku-ui#515]
## User Story
As a user, I want to group by tag keys and see associated tags in the AWS/OCP detail pages.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- Sort by tag name not supported: https://github.com/project-koku/koku/issues/714
- Show 'Others' not supported: https://github.com/project-koku/koku/issues/715
- Show cluster in details not supported: https://github.com/project-koku/koku/issues/711

## UI Details
Currently, we apply the group_by[tag:xxx] query parameter via the 'Group By' dropdown menu. However, we also 'Group By' project, so we're not showing the correct information. We need to refactor this functionality to show tags associated with the selected tag key, while ensuring sorting and filterng continue to work properly.

Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350493391

![screen shot 2019-03-07 at 10 33 26 am](https://user-images.githubusercontent.com/17481322/53969935-ac021d00-40c7-11e9-88f2-0f52728db889.png)

## Acceptance Criteria
- [x] Expandable rows are available.
- [x] Group by lists tags associated with the selected tag key, not projects
- [x] Tags are filterable when group_by is applied
- [x] Export icon should work when group_by tag key is applied
- [x] Sort by cost supported
- [x] Show fixed total cost at top right

## Epic Issues
https://app.zenhub.com/workspaces/project-koku-5ab50f63d0f4ea53b00232c8/issues/project-koku/koku-ui/515

**Comment by dlabrecq** [comment]
The 'Other' row will not be implemented in the UI until we have a server-side solution.

Note that the group_by tags API appears to be broken ATM.
See https://github.com/project-koku/koku/issues/720

**Comment by dchorvat1** [comment]
About the sort-by-cost, when we apply group by tag, we get the list items sorted by cost, but we don't get the option of changing it by ascending/descending. Was this behavior expected?

**Comment by dlabrecq** [comment]
I opened a new issue to fix the sort problem. It's a simple fix.

https://github.com/project-koku/koku-ui/issues/625

**Comment by dlabrecq** [comment]
Created PR https://github.com/project-koku/koku-ui/pull/626

**Comment by dlabrecq** [comment]
Merged

**Comment by dchorvat1** [comment]
Verified
Commit: 1747754
